Create CI/CD

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -62,9 +62,18 @@ jobs:
         echo "REDIS_BACKEND=${{ secrets.REDIS_BACKEND }}" >> .env
         echo "REDIS_LOCATION=${{ secrets.REDIS_LOCATION }}" >> .env
 
+    - name: Add delay before checks
+      run: sleep 15
+
+    - name: Check PostgreSQL version
+      run: docker run --rm postgres:15 pg_isready
+
+    - name: Show PostgreSQL logs
+      run: docker logs postgres || true
+
     - name: Check DNS resolution for PostgreSQL
       run: |
-        ping -c 3 postgres || (echo "Failed to resolve 'postgres'" && exit 1)
+        nslookup -c 3 postgres || (echo "Failed to resolve 'postgres'" && exit 1)
 
     - name: Show PostgreSQL container status
       run: docker ps -a
@@ -77,15 +86,19 @@ jobs:
           echo "PostgreSQL container is not running yet."
         fi
 
-    - name: Wait for PostgreSQL to be ready
+    - name: Wait for PostgreSQL to be ready (HEALTHCHECK)
+      run: |
+        until docker inspect -f '{{.State.Health.Status}}' postgres | grep -q "healthy"; do
+          echo "Waiting for PostgreSQL HEALTHCHECK..."
+          sleep 5
+        done
+
+    - name: Wait for PostgreSQL to be ready (psql)
       run: |
         until psql -h postgres -U ${{ secrets.DB_USER }} -c '\l'; do
           echo "Waiting for PostgreSQL..."
           sleep 5
         done
-
-    - name: Show PostgreSQL logs
-      run: docker logs postgres || true
 
     - name: Run migrations
       run: poetry run python manage.py migrate
